site_name: ANAC Docs
theme:
  name: material
  language: pt
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
plugins:
#  - search:
#      lang: pt
#        - en
#        - es
#     separator: '[\s\-\.]+'
#  - git-revision-date
#      enabled_if_env: CI
#  - git-revision-date-localized
google_analytics:
  - G-ZDZEMGKM6S
  - auto
extra:
  social:
    - icon: fontawesome/brands/wikipedia-w
      link: https://sistemas.anac.gov.br/wiki
      name: WikiANAC 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/oficial-anac
      name: Linkedin
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/oficial_Anac
      name: Twitter
copyright: CC0 - Domínio Público - https://creativecommons.org/publicdomain/zero/1.0/deed.pt_BR
repo_url: https://github.com/gabrielmacedo/anac
repo_name: ANAC Docs no Github
markdown_extensions:
  - meta